name: Build Windows Executable

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHONNODEBUGRANGES: 1

jobs:
  build_windows:
    name: Build Windows binary
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        architecture: "x64"
        cache: pip
        cache-dependency-path: "**/requirements.txt"
    - name: Install Python dependencies
      # Without dependencies to make sure everything is covered in the requirements.txt
      run: |
        python --version
        python -m pip install --upgrade pip wheel
        pip install --upgrade -r requirements.txt --no-dependencies
        pip install --upgrade -r builder/requirements.txt --no-dependencies
    - name: Build Windows standalone binary and installer
      run: python builder/package.py installer
    - name: Upload Windows standalone binary
      uses: actions/upload-artifact@v4
      with:
        path: "*-win64-bin.zip"
        name: Windows standalone binary
